name: meetingreminder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  android_alarm_manager_plus: ^4.0.4
  flutter_local_notifications: ^18.0.1
  flutter_ringtone_player: ^3.2.0
  timezone: ^0.10.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/home-page.png
    - assets/images/icons/clock(1).png
