# Generated by Django 5.1.3 on 2024-12-02 09:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='meeting',
            name='alarm_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='alarm_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Untitled Meeting', max_length=255),
        ),
    ]
